### ISSUE TITLE
Share .prettierrc to make code formatting more consistent across contributions

### ISSUE THREAD

**Issue by jozsr** [webNeat/react-tidy#26]
See title. :smile:

**Comment by webNeat** [comment]
Hey @jozsr 
The Prettier configuration is included inside `package.json` https://github.com/webNeat/react-tidy/blob/master/package.json#L25
Do you think that having it in a separated file is better?

**Comment by jozsr** [comment]
Ah, missed that, sorry.
I'm in favour of a separate file, but it's just cosmetic I guess.
One reason is that if you want to share it, you can just send the file, instead of having to open the package.json and copy&paste it.
The second is that if you want a .prettierignore file, that needs to be separate as well.
So basically it's just my personal preference to have separated files for different purposes.
eslintrc, eslintignore, prettierrc, prettierignore,  editorconfig, etc...
I only use package.json for npm related stuff (dependencies and scripts).

**Comment by webNeat** [comment]
I don't have a specific preference. Since this confused you, it may confuse other people as well so I added `.prettierrc` and `.editorconfig` files.
