### ISSUE TITLE
Can't import the named export 'useMemo' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by turkiasoft** [webNeat/react-tidy#40]
"dependencies": {
    "@date-io/date-fns": "^1.3.13",
    "@emotion/styled": "^11.6.0",
    "@hookform/resolvers": "^2.8.0",
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.60",
    "@material-ui/pickers": "^3.3.10",
    "@mui-treasury/styles": "^1.13.1",
    "@mui/icons-material": "^5.3.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "autosuggest-highlight": "^3.1.1",
    "axios": "^0.21.1",
    "clsx": "^1.1.1",
    "date-fns": "^2.23.0",
    "libphonenumber-js": "^1.9.24",
    "material-design-icons": "^3.0.1",
    "material-table": "^1.69.3",
    "material-ui-dropzone": "^3.5.0",
    "material-ui-popup-state": "^1.9.3",
    "moment": "^2.29.1",
    "notistack": "^1.0.10",
    "react": "^17.0.2",
    "react-big-calendar": "^0.36.1",
    "react-datepicker": "^4.2.1",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.12.2",
    "react-phone-input-material-ui": "^2.16.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-select": "^4.3.1",
    "react-svg-radar-chart": "1.3.0",
    "react-tidy": "^1.3.3",
    "react-tooltip": "^4.2.21",
    "react-wait": "^0.3.0",
    "react-window": "^1.8.6",
    "styled-components": "^5.3.0",
    "survey-pdf": "^1.8.63",
    "survey-react": "^1.8.58",
    "sweetalert2": "^11.1.7",
    "sweetalert2-react-content": "^4.1.1",
    "valtio": "^1.1.3",
    "web-vitals": "^1.0.1",
    "yup": "^0.32.9",
    "yup-phone": "^1.2.19"
  },

**Comment by webNeat** [comment]
Hello @turkiasoft thank you for the issue but I need more details to be able to reproduce it.
- Can you please share the code that triggers the error? (`useMemo` is part of `react` not `react-tidy`)
- Are you using `create-react-app` with default configuration or are you using custom configuration?

**Comment by webNeat** [comment]
Ok, I was able to reproduce this issue using the specific version `4.0.3` of `react-scripts`. The error was that this version didn't support esm well.

I released a fix in version `1.3.4`, please try upgrading to this version and let me know if that fixes your issue.
